[package]
name = "kernel"
version = "0.1.0"
authors = ["IsaacDynamo"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spin = "0.9.3"
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }